### ISSUE TITLE
bot_bundle error

### ISSUE THREAD

**Issue by tanercanbilgin** [dapucita/haxbotron#152]
2021-05-11 00:01:51|error| [futsal] Error: TypeError: Cannot read property 'id' of undefined
    at Object.o.recuritByOne (./out/bot_bundle.js:1:102152)
    at Object.o.onPlayerLeaveListener (./out/bot_bundle.js:1:81090)
    at window.gameRoom._room.onPlayerLeave (./out/bot_bundle.js:1:2629)
    at u.sh (https://www.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:66:137)
    at Function.Da.va (https://www.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:53:228)
    at I.apply (https://www.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:113:254)
    at Fa.nf (https://www.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:45:101)
    at Fa.ec (https://www.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:46:144)
    at A.mh (https://www.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:63:497)
    at Function.ua.va (https://www.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:53:81)
    
every time i open a room it gives this error and destroying automation of bot, for example someone playing and quitting. when they want to join back it says you are already in game. do you know why it happens?

**Comment by dapucita** [comment]
This problem does not exist on the server that has been in testing for months now.
Maybe there are something wrong when you started the bot.

**Comment by tanercanbilgin** [comment]
when i play it manuel there is no error like this but these days im starting from my vds and this error happens everytime and i cant track my rooms with correct numbers. it shows 37 player in only 1 game, sometimes we have bug and we cant join again. i did installation from zero and it still happens

**Comment by tanercanbilgin** [comment]
https://imgur.com/SEicZ7N thats what i see when i want to build core

**Comment by tanercanbilgin** [comment]
> when i play it manuel there is no error like this but these days im starting from my vds and this error happens everytime and i cant track my rooms with correct numbers. it shows 37 player in only 1 game, sometimes we have bug and we cant join again. i did installation from zero and it still happens

 when they cant join it gives error from this message doubleJoinningKick

**Comment by dapucita** [comment]
It is difficult to help, because such problem cannot be reproduced equally on other servers.

Maybe it's an internet problem.

I'm sorry I couldn't help you because I've been busy these days.

**Comment by tanercanbilgin** [comment]
yes bro i agree, when i was running server from my computer there was no error. now im on vds and it happens a lot, is it because of ports allowed? its okay i can wait you for a better time :)

**Comment by dapucita** [comment]
I have no ideas cuz idk your environment
and there were no problems in other cases :)

**Comment by tanercanbilgin** [comment]
its a vds with ubuntu 18.04, i also tried to make a new account for bot to run it. it also didnt work, we have 1000mbps internet and ssd. maybe im installing nodejs wrong, which ways you followed in linux based servers

**Comment by tanercanbilgin** [comment]
i bought one more vds and i still got same error, i tried all the possibilities and i just want to cry...
